export enum EPaymentStatus {
  READY = 'READY',
  PENDING = 'PENDING',
  VIRTUAL_ACCOUNT_ISSUED = 'VIRTUAL_ACCOUNT_ISSUED',
  PAID = 'PAID',
  FAILED = 'FAILED',
  PARTIAL_CANCELLED = 'PARTIAL_CANCELLED',
  CANCELLED = 'CANCELLED'
}
